### ISSUE TITLE
Composition Barplot

### ISSUE THREAD

**Issue by MycoMap** [tbj128/mian#4]
When creating a boxplot that is filtered by metadata, the groups of metadata that are excluded still appear in the legend and x-axis. They will always be zero, so it would only make sense to not plot them.

Also, the alignment is off on the x-axis.

![image](https://user-images.githubusercontent.com/11707715/56622308-7bd1f780-65fd-11e9-864d-0284ab047e81.png)

**Comment by MycoMap** [comment]
It would also be great to have an option to compare the groups side-by-side, rather than as a stacked barplot.

**Comment by tbj128** [comment]
Thank you for your suggestion! I agree that having a side-by-side grouping would be a useful view to have. Initially, I think it was a side-by-side grouping but it was changed to a stacked bar because of how large the graphs would get if there were a lot of taxonomic groups. 

Commit fbfb37d included a change that gives users the option to choose between a stacked and a side-by-side barplot as shown in the screenshot below.

Commit cf638d2 removed unnecessary columns that were being displayed when they had zero values. 

![image](https://user-images.githubusercontent.com/3182382/64484369-d4c5b500-d1c5-11e9-9c58-b6d5161b91b6.png)

**Comment by tbj128** [comment]
Please re-open if you feel that this feature could still be improved further :)
